import fs from 'node:fs/promises';
import path from 'node:path';

import { addLesson } from './lessons.js';
import { qaAnswerFromEvidence } from './qaAgent.js';
import { searchCode } from './retriever.js';

type OutputTarget = 'docs' | 'lessons' | 'both';

const DEFAULT_GROUPS = ['mcp-server', 'mcp-auth', 'config', 'embeddings', 'indexing', 'queue', 'kg'];

function mdEscape(s: string) {
  return s.replace(/\r\n/g, '\n').trim();
}

export async function buildFaq(input: {
  projectId: string;
  root: string;
  modules?: string[];
  maxItems?: number;
  outputTarget?: OutputTarget;
}): Promise<{ status: 'ok'; written_files: string[]; items: number }> {
  const outTarget: OutputTarget = (input.outputTarget ?? 'both') as OutputTarget;
  const maxItems = Math.max(1, Math.min(Number(input.maxItems ?? 30), 200));
  const groups = (input.modules?.length ? input.modules : DEFAULT_GROUPS).map(s => String(s));

  // Seed FAQ prompts from our golden set (best-effort): keep this self-contained.
  const prompts: Array<{ group: string; q: string; pathGlob?: string }> = [
    { group: 'mcp-server', q: 'Where is the MCP HTTP endpoint implemented and how are tools registered?', pathGlob: 'src/**/*.ts' },
    { group: 'mcp-auth', q: 'Where is workspace_token validated for MCP tool calls?', pathGlob: 'src/**/*.ts' },
    { group: 'config', q: 'Where are environment variables validated and what are the defaults?', pathGlob: 'src/**/*.ts' },
    { group: 'embeddings', q: 'How does the embeddings client call /v1/embeddings and validate dimensions?', pathGlob: 'src/**/*.ts' },
    { group: 'indexing', q: 'How does index_project discover files, chunk, embed, and write to Postgres?', pathGlob: 'src/**/*.ts' },
    { group: 'queue', q: 'How are async jobs enqueued and claimed (postgres + rabbitmq)?', pathGlob: 'src/**/*.ts' },
    { group: 'kg', q: 'How is the Knowledge Graph (Neo4j) bootstrapped and queried?', pathGlob: 'src/**/*.ts' },
  ].filter(p => groups.includes(p.group));

  const selected = prompts.slice(0, maxItems);
  const byGroup = new Map<string, typeof selected>();
  for (const p of selected) {
    const arr = byGroup.get(p.group) ?? [];
    arr.push(p);
    byGroup.set(p.group, arr);
  }

  const written: string[] = [];
  const docsDir = path.join(input.root, 'docs', 'faq');
  if (outTarget === 'docs' || outTarget === 'both') {
    await fs.mkdir(docsDir, { recursive: true });
  }

  for (const [group, items] of byGroup.entries()) {
    const lines: string[] = [];
    lines.push(`# FAQ — ${group}`);
    lines.push('');
    lines.push(`Generated by worker job \`faq.build\` for project \`${input.projectId}\`.`);
    lines.push('');

    for (const it of items) {
      const r = await searchCode({
        projectId: input.projectId,
        query: it.q,
        pathGlob: it.pathGlob,
        kgAssist: group === 'kg' || group === 'queue' || group === 'mcp-server',
        lexicalBoost: true,
        limit: 8,
        debug: false,
      });
      const top = r.matches.slice(0, 3);
      const cites = Array.from(new Set(top.map(m => m.path)));
      const answer = await qaAnswerFromEvidence({
        question: it.q,
        evidence: top.map(m => ({ path: m.path, snippet: m.snippet })),
        maxChars: 2200,
      });

      lines.push(`## Q: ${mdEscape(it.q)}`);
      lines.push('');
      lines.push(`**Evidence files**: ${cites.map(c => `\`${c}\``).join(', ') || '(none)'}`);
      lines.push('');
      if (answer) {
        lines.push(`**Answer (QA agent)**: ${mdEscape(answer)}`);
        lines.push('');
      }
      for (const m of top) {
        lines.push(`- \`${m.path}\` (lines ${m.start_line}-${m.end_line}, score ${m.score.toFixed(3)}): ${mdEscape(m.snippet)}`);
      }
      lines.push('');

      if (outTarget === 'lessons' || outTarget === 'both') {
        const content =
          `Q: ${it.q}\n\n` +
          `Evidence:\n${top.map(m => `- ${m.path} (${m.start_line}-${m.end_line}): ${m.snippet}`).join('\n')}\n`;
        await addLesson({
          project_id: input.projectId,
          lesson_type: 'general_note',
          title: `FAQ: ${it.q}`.slice(0, 120),
          content,
          tags: ['faq', group],
          source_refs: cites,
          captured_by: 'faq.build',
        });
      }
    }

    if (outTarget === 'docs' || outTarget === 'both') {
      const outPath = path.join(docsDir, `${group}.md`);
      await fs.writeFile(outPath, lines.join('\n'), 'utf8');
      written.push(outPath);
    }
  }

  return { status: 'ok', written_files: written.map(p => p.replace(/\\/g, '/')), items: selected.length };
}

