-- Add search_aliases column for alternative phrasings that improve search recall.
-- Generated by LLM at add_lesson time: question form, keywords, synonyms.
-- Included in FTS index and embedding for wider vocabulary coverage.

ALTER TABLE lessons ADD COLUMN IF NOT EXISTS search_aliases text;
